/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

/**
 *
 * @author guillermo.barchino
 */

import Modelo.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;

public class VentanaSocio extends javax.swing.JFrame {
    
    
    private Gimnasio miGimnasio;
    private Socio socioActual;


    /**
     * Creates new form VentanaSocio
     */
    public VentanaSocio(Gimnasio gym, Socio socio) {
        initComponents();
        
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        
        tblActividades.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblReservas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        this.miGimnasio = gym;
        this.socioActual = socio;

        cargarTablaActividades();
        cargarTablaReservas();
        
        btnCerrarSesion.addActionListener(evt -> {
             miGimnasio.guardarDatos();
             new VentanaLog().setVisible(true);
             this.dispose();
        });


    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActividades = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel2.setText("Panel de Administrador:");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel4.setText("Panel de Socio:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Título", "Tipo", "Monitor", "Sala", "Especial"
            }
        ));
        jScrollPane1.setViewportView(tblActividades);

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Actividad", "Fecha", "Dia", "Importe"
            }
        ));
        jScrollPane2.setViewportView(tblReservas);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel3.setText("Tabla Actividades");

        btnReservar.setText("Reservar");
        btnReservar.addActionListener(this::btnReservarActionPerformed);

        btnCancelar.setText("Cancelar");

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarSesion.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel5.setText("Panel de Socio:");

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel6.setText("Panel de Socio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnCerrarSesion)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReservar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
    int fila = tblActividades.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una actividad");
        return;
    }

    Actividad act = miGimnasio.getActividades().get(fila);
    Horarios horario = act.getHorarios().get(0);

    LocalDate fecha = LocalDate.now();
    
    while (true) {
    if (convertirDia(horario.getDia()) == fecha.getDayOfWeek()) {
        break;
    }
    fecha = fecha.plusDays(1);
}

    boolean exito = miGimnasio.reservarActividad(socioActual, act, horario, fecha);

    if (exito) {
        JOptionPane.showMessageDialog(this, "Reserva realizada");
        cargarTablaReservas();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo reservar");
    }

    }//GEN-LAST:event_btnReservarActionPerformed
    private void cargarTablaActividades() {
    DefaultTableModel modelo = (DefaultTableModel) tblActividades.getModel();
    modelo.setRowCount(0);

    for (Actividad act : miGimnasio.getActividades()) {
        String especial = (act instanceof ActividadEspecial) ? "Sí" : "No";

        Object[] fila = {
            act.getTitulo(),
            act.getTipo(),
            act.getMonitor(),
            act.getSala().getNombre(),
            especial
        };

        modelo.addRow(fila);
    }
}
    private void cargarTablaReservas() {
    DefaultTableModel modelo = (DefaultTableModel) tblReservas.getModel();
    modelo.setRowCount(0);

    for (Reserva r : socioActual.getReservas()) {
        Object[] fila = {
            r.getActividad().getTitulo(),
            r.getFecha(),
            r.getHorario().getDia(),
            r.getImporte()
        };

        modelo.addRow(fila);
    }
}
    private java.time.DayOfWeek convertirDia(DiaSemana dia) {
    return switch (dia) {
        case LUNES -> java.time.DayOfWeek.MONDAY;
        case MARTES -> java.time.DayOfWeek.TUESDAY;
        case MIERCOLES -> java.time.DayOfWeek.WEDNESDAY;
        case JUEVES -> java.time.DayOfWeek.THURSDAY;
        case VIERNES -> java.time.DayOfWeek.FRIDAY;
        case SABADO -> java.time.DayOfWeek.SATURDAY;
        case DOMINGO -> java.time.DayOfWeek.SUNDAY;
    };
}

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {

    int fila = tblReservas.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una reserva");
        return;
    }

    Reserva r = socioActual.getReservas().get(fila);

    socioActual.cancelarReserva(r);
    miGimnasio.getReservas().remove(r);

    JOptionPane.showMessageDialog(this, "Reserva cancelada");

    cargarTablaReservas();
}
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnReservar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblActividades;
    private javax.swing.JTable tblReservas;
    // End of variables declaration//GEN-END:variables
}
