/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;
import Modelo.*;
/**
 *
 * @author monto
 */
public class VentanaAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAdmin.class.getName());

    /**
     * Creates new form VentanaAdmin
     */
    private Gimnasio miGimnasio;
    
    public VentanaAdmin(Gimnasio gym) {
        initComponents();
        this.miGimnasio = gym;
        
        btnCerrarSesion.addActionListener(evt -> {
             miGimnasio.guardarDatos();
             new VentanaLog().setVisible(true);
             this.dispose();
        });
        
        cargarTablaActividades();
        cargarTablaSocios();
        cargarTablaReservas();
        refrescarYGuardar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActividades = new javax.swing.JTable();
        btnAñadirAct = new javax.swing.JButton();
        btnModificarAct = new javax.swing.JButton();
        btnEliminarAct = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSocios = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel2.setText("Panel de Administrador:");

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarSesion.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        tblActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Tipo", "Monitor", "Sala", "Especial"
            }
        ));
        jScrollPane1.setViewportView(tblActividades);

        btnAñadirAct.setText("Añadir Nueva Actividad");
        btnAñadirAct.addActionListener(this::btnAñadirActActionPerformed);

        btnModificarAct.setText("Modificar Actividad");
        btnModificarAct.addActionListener(this::btnModificarActActionPerformed);

        btnEliminarAct.setText("Eliminar Actividad");
        btnEliminarAct.addActionListener(this::btnEliminarActActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnAñadirAct)
                .addGap(36, 36, 36)
                .addComponent(btnModificarAct, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnEliminarAct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadirAct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarAct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarAct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actividades", jPanel2);

        tblSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Correo", "Teléfono", "Dirección", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(tblSocios);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de Socios", jPanel3);

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Socio", "Actividad", "Fecha", "Horario", "Importe"
            }
        ));
        jScrollPane3.setViewportView(tblReservas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jTabbedPane1.addTab("Registro de Reservas", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(btnCerrarSesion)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(450, 80, 714, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActActionPerformed
        int filaSeleccionada = tblActividades.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona una actividad de la tabla primero.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar esta actividad?", "Confirmar borrado", javax.swing.JOptionPane.YES_NO_OPTION);
        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            // 4. Borramos la actividad de la lista real del gimnasio
            miGimnasio.getActividades().remove(filaSeleccionada);
            refrescarYGuardar();
    
            javax.swing.JOptionPane.showMessageDialog(this, "Actividad eliminada con éxito.");
}
    }//GEN-LAST:event_btnEliminarActActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnAñadirActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActActionPerformed
        DialogoActividad ventanaNueva = new DialogoActividad(this, true, miGimnasio);
        ventanaNueva.setVisible(true); 
        refrescarYGuardar();

    }//GEN-LAST:event_btnAñadirActActionPerformed

    private void btnModificarActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActActionPerformed
        int filaSeleccionada = tblActividades.getSelectedRow();


    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona una actividad de la tabla primero.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // 
    }
    Modelo.Actividad actividadElegida = miGimnasio.getActividades().get(filaSeleccionada);
    DialogoModificarActividad ventanaModificar = new DialogoModificarActividad(this, true, miGimnasio, actividadElegida, filaSeleccionada);
    ventanaModificar.setVisible(true);
    refrescarYGuardar();
    }//GEN-LAST:event_btnModificarActActionPerformed
    private void cargarTablaActividades() {
    // 1. Enganchamos el "cable HDMI" (El Modelo) de tu tabla
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblActividades.getModel();
    
    // 2. Borramos las filas de prueba que NetBeans pone por defecto
    modelo.setRowCount(0);
    
    // 3. Le pedimos al gimnasio su lista de actividades y la recorremos
    for (Modelo.Actividad act : miGimnasio.getActividades()) {
        
        // Comprobamos si es VIP/Especial para poner "Sí" o "No" en la última columna
        String esEspecial = "No";
        if (act instanceof Modelo.ActividadEspecial) {
            esEspecial = "Sí";
        }
        
        // 4. Preparamos una "fila" con los datos exactos de esta actividad
        Object[] fila = {
            act.getTitulo(),
            act.getTipo().toString(),
            act.getMonitor(),
            act.getSala().getNombre(),
            esEspecial
        };
        
        // 5. Añadimos la fila al modelo, y la tabla se actualizará sola
        modelo.addRow(fila);
    }
}
    private void cargarTablaSocios() {
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblSocios.getModel();
    modelo.setRowCount(0); // Limpiar tabla
    
    for (Modelo.Usuario u : miGimnasio.getUsuarios()) {
        if (u instanceof Modelo.Socio) {
            Modelo.Socio socio = (Modelo.Socio) u; // Casteo para poder usar sus métodos
            
            Object[] fila = {
                socio.getNombre(),
                socio.getCorreo(),
                socio.getTelefono(),
                socio.getDireccion(),
                socio.getTipo().toString()
            };
            modelo.addRow(fila);
        }
    }
}
    private void cargarTablaReservas() {
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblReservas.getModel();
    modelo.setRowCount(0); // Limpiar tabla
    
    for (Modelo.Reserva r : miGimnasio.getReservas()) {
        Object[] fila = {
            r.getSocio().getNombre(),
            r.getActividad().getTitulo(),
            r.getFecha().toString(),
            r.getHorario().getHoraInicio().toString() + " - " + r.getHorario().getHoraFin().toString(), 
            r.getImporte()
        };
        modelo.addRow(fila);
    }
}
    private void refrescarYGuardar() {
    // 1. Refresca la tabla para que se vea el cambio visualmente
    cargarTablaActividades(); 
    
    miGimnasio.guardarDatos(); 
}
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirAct;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEliminarAct;
    private javax.swing.JButton btnModificarAct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblActividades;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTable tblSocios;
    // End of variables declaration//GEN-END:variables
}

